# Generated by Django 4.0 on 2022-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videoclub', '0003_socio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='disponibilidad',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio',
            field=models.CharField(max_length=100),
        ),
    ]
