# Generated by Django 4.0.2 on 2022-02-15 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Videoclub', '0004_remove_pelicula_disponibilidad_alter_pelicula_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nro_socio',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
